// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHVZstnfBCc8MO3fUiCBWsrz_Xr-uONCk',
    appId: '1:192931243011:web:45ac8c86ea542ba4dc1a36',
    messagingSenderId: '192931243011',
    projectId: 'manajemen-aset-df9aa',
    authDomain: 'manajemen-aset-df9aa.firebaseapp.com',
    storageBucket: 'manajemen-aset-df9aa.firebasestorage.app',
    measurementId: 'G-JN0VVJ87XB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMn2pZlkWG7ItrhKho4sGkbW95ArDfgp0',
    appId: '1:192931243011:android:7eef87934fd0345cdc1a36',
    messagingSenderId: '192931243011',
    projectId: 'manajemen-aset-df9aa',
    storageBucket: 'manajemen-aset-df9aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGptN8C7KOGxcj3pvrIEBUz1_1dO_qEMo',
    appId: '1:192931243011:ios:b8082abf91b7218bdc1a36',
    messagingSenderId: '192931243011',
    projectId: 'manajemen-aset-df9aa',
    storageBucket: 'manajemen-aset-df9aa.firebasestorage.app',
    iosBundleId: 'edu.itenas.manajemenAset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGptN8C7KOGxcj3pvrIEBUz1_1dO_qEMo',
    appId: '1:192931243011:ios:b8082abf91b7218bdc1a36',
    messagingSenderId: '192931243011',
    projectId: 'manajemen-aset-df9aa',
    storageBucket: 'manajemen-aset-df9aa.firebasestorage.app',
    iosBundleId: 'edu.itenas.manajemenAset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHVZstnfBCc8MO3fUiCBWsrz_Xr-uONCk',
    appId: '1:192931243011:web:315417e2932d484adc1a36',
    messagingSenderId: '192931243011',
    projectId: 'manajemen-aset-df9aa',
    authDomain: 'manajemen-aset-df9aa.firebaseapp.com',
    storageBucket: 'manajemen-aset-df9aa.firebasestorage.app',
    measurementId: 'G-1VJY9Z92DC',
  );

}